### ISSUE TITLE
Error when running ICBasedSimilarity

### ISSUE THREAD

**Issue by mhsteppan** [Blubberli/germanetTutorials#5]
Hello,

I am struggling to run the code example von ICBasedSimilarity. The following error occurs:

Traceback (most recent call last):
  File "<pyshell#153>", line 1, in <module>
    relatedness_nouns = ICBasedSimilarity(germanet=germanet, wordcategory=WordCategory.nomen, path=frequencylist_nouns)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\germanetpy\icbased_similarity.py", line 35, in __init__
    self.create_simple_freq_dic(wordcategory, path, separator)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\germanetpy\icbased_similarity.py", line 59, in create_simple_freq_dic
    for line in f:
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1424: character maps to <undefined>

Do you know what the problem might be?

Kind regards,
Martin

**Comment by bencampbell30** [comment]
Hi Martin,

Unfortunately there are some known issues that occur when trying to use germanetpy with Windows. What kind of chip do you have? We tried getting it working last year with Windows on two separate machines, one with an AMD processor and one with an Intel. On the Intel machine we were able to get it partially working but still with some errors while it did not work at all on the AMD machine.

There are, however, a few things you could try: first, try using the latest version of the germanetpy package, 0.2.2. This was created last year but only just today officially released.

https://pypi.org/project/germanetpy/

On Windows you may need to build the python-Levenshtein package, a required dependency, locally. For this you will need to install Visual C++ version 14.0 or later (with SDK and c++ build tools), if it is not already installed:

https://www.scivision.dev/python-windows-visual-c-14-required/

If this works or you otherwise manage to get it working, please let us know, as it would be helpful in the future for others who cannot get germanetpy working on Windows.

Best regards,

Ben
